1485 task8 responsive design enhancement
Sanaiqbal-dev/portfolio-project pull request #9
Opened 2023-10-26 11:47 UTC by Sanaiqbal-dev

Task 8 is complete.
User Story : https://dev.azure.com/CodeNinjaConsulting/Talent%20Pool/_workitems/edit/1426

2023-10-27 07:44 UTC, huzaifah0x00 requested changes

2023-10-27 07:44 UTC, huzaifah0x00 commented on styles.css
Can you please break this file down into multiple css files. having only one css file makes it very hard to maintain and read.

it seems you have different pages in the project ( data view, signup, portfolio, etc ), you should have separate file for 
different pages and include that css with <link> in each html file.

if you have some styles that need to be used by multiple files, you can put those in a common css file.
but css that is only used by a specific page should only be included in that html page.

2023-10-27 07:47 UTC, huzaifah0x00 commented on styles.css
I will review the rest of the PR once this is done.

2023-10-30 09:57 UTC, huzaifah0x00 approved these changes
@Sanaiqbal-dev I've approved the pull request, the responsivess part looks good :thumbsup: 
One thing though, I noticed a bug that once you edit and add new experiences, the new experiences don't show up in the homepage, only in the edit page. ( please let me know if I'm wrong ). This is something you should fix ( not necessary as part of this PR, feel free to merge this one and create a new PR for that later ).

2023-10-30 10:01 UTC, Sanaiqbal-dev commented
> @Sanaiqbal-dev I've approved the pull request, the responsivess part looks good 👍 One thing though, I noticed a bug that once you edit and add new experiences, the new experiences don't show up in the homepage, only in the edit page. ( please let me know if I'm wrong ). This is something you should fix ( not necessary as part of this PR, feel free to merge this one and create a new PR for that later ).

2023-10-30 10:04 UTC, Sanaiqbal-dev commented
> > @Sanaiqbal-dev I've approved the pull request, the responsivess part looks good 👍 One thing though, I noticed a bug that once you edit and add new experiences, the new experiences don't show up in the homepage, only in the edit page. ( please let me know if I'm wrong ). This is something you should fix ( not necessary as part of this PR, feel free to merge this one and create a new PR for that later ).

2023-10-30 10:04 UTC, merged

2023-10-30 10:07 UTC, Sanaiqbal-dev commented
> @Sanaiqbal-dev I've approved the pull request, the responsivess part looks good 👍 One thing though, I noticed a bug that once you edit and add new experiences, the new experiences don't show up in the homepage, only in the edit page. ( please let me know if I'm wrong ). This is something you should fix ( not necessary as part of this PR, feel free to merge this one and create a new PR for that later ).

Thanks for approving the PR, and pointing out a potential bug. I have noticed it while working on my current task and the bug is related to it. I'll make sure that it is fixed in next PR.